### PR TITLE
Remove dependency from MaxMind Geo ASN/City database

### PR DESCRIPTION
**Pull request by lscorcia**
Removes the dependency from MaxMind Geo ASN/City database as proposed in https://github.com/OpenIdentityPlatform/OpenAM/issues/230 .

### CODE REVIEW

**Comment by maximthomas** [comment]
It is possible to build forgerock-commons with this pull request, but we are loosing information about clients IP address in logs so there are fewer factors to analyse for adaptive authentication. May be we should contact MaxMind to get access to their geo database?

**Comment by lscorcia** [comment]
Actually it seems that this httpdump component is only used in the ReCaptcha implementation, so I don't think that we're losing anything regarding adaptive auth (https://github.com/OpenIdentityPlatform/OpenAM/search?q=httpdump&unscoped_q=httpdump).
In fact, OpenAM has a user-configuration section dedicated to supplying the path for the adaptive auth database (and it uses the Country one, not the ASN nor the City one):

immagine

If for any reason we want to keep the dependency on the geo db, I think that we could imagine a configuration setting like the above one for recaptcha, so that any interested user could request his own license for his copy of the data.

**Comment by vharseko** [comment]
please check https://github.com/OpenIdentityPlatform/OpenAM/issues/230

**Comment by lscorcia** [comment]
Thanks for fixing the build issue, but could you please help me understand why those huge dependencies (around 33 MB) are embedded into the project, seeing that they're used exactly at one line of the code, which happens to be an error handler in the recaptcha component? Maybe I'm missing some indirect reference?

**Pull request closed without merging**
